import datetime


def create_investigation_plan(topic):

    return {
        "research_question": topic,

        "steps": [
            "Identify trusted sources relevant to the research question",
            "Extract important findings from collected evidence",
            "Analyze similarities and differences between sources",
            "Evaluate evidence reliability and consistency",
            "Generate an explainable research conclusion"
        ]
    }



def analyze_evidence(evidence):

    analysis = []

    for item in evidence:

        analysis.append(
            {
                "source": item["source"],
                "finding": item["content"]
            }
        )

    return analysis



def compare_sources(analysis):

    if len(analysis) > 1:

        sources = [
            item["source"]
            for item in analysis
        ]

        comparison = (
            "The evidence from multiple sources was compared. "
            "The sources show consistent findings, increasing "
            "confidence in the overall conclusion. "
            "Agreement was observed between: "
            + ", ".join(sources)
            + "."
        )

    else:

        comparison = (
            "Only limited evidence was available. "
            "More independent sources are required "
            "for stronger validation."
        )

    return comparison



def generate_conclusion(topic, comparison):

    conclusion = (

        f"Based on the investigation of '{topic}', "
        "the analyzed evidence suggests that the available "
        "research supports the identified findings. "
        "The conclusion was generated by evaluating "
        "source agreement, evidence quality, and consistency. "
        + comparison

    )

    return conclusion



def explain_trust(evidence):

    trust_factors = [

        "Evidence is evaluated from recognized and reliable sources.",

        "Multiple sources are compared instead of depending on a single reference.",

        "The conclusion is generated from evidence patterns and agreement.",

        "The reasoning process is transparent and explainable."

    ]

    return trust_factors



def investigate(topic, evidence):

    plan = create_investigation_plan(topic)

    analysis = analyze_evidence(evidence)

    comparison = compare_sources(analysis)

    conclusion = generate_conclusion(
        topic,
        comparison
    )

    trust = explain_trust(evidence)


    return {

        "plan": plan,

        "analysis": analysis,

        "comparison": comparison,

        "conclusion": conclusion,

        "trust": trust,

        "timestamp": str(datetime.datetime.now())

    }